### PR TITLE
Remove settings option

### PR DESCRIPTION
**Pull request by rahmatsyam**
I just comment your function option to disable it

### CODE REVIEW

**Review by ajay-prabhakar — COMMENTED** [review]
Can you please update the branch properly

**Comment by rahmatsyam** [comment]
I don't think this branch no conflict

**Comment by rahmatsyam** [comment]
I think this branch no conflict

**Comment by ajay-prabhakar** [comment]
> I think this branch no conflict

I dont mean conflicts
As you are working on master branch itself there are previous commits also so
Please so git fetch and git pull

**Comment by rahmatsyam** [comment]
Yeah, I have aleady pull from master before make PR

**Comment by rahmatsyam** [comment]
image

**Comment by ajay-prabhakar** [comment]
You fetched it from origin but add the remote of upstream and then fetch it and pull

**Comment by rahmatsyam** [comment]
I have already add remote upstream , fetch and pull it. What is next, frend?

**Comment by ajay-prabhakar** [comment]
> I have already add remote upstream , fetch and pull it. What is next, frend?

Yeah, then push it

**Comment by rahmatsyam** [comment]
Okay, I have already push it

**Comment by ajay-prabhakar** [comment]
@rahmatsyam are you still working on this?

**Comment by rahmatsyam** [comment]
No friend

**Pull request closed without merging**
