### PR TITLE
added design changes and colors for fixing #8 and also added ACRA Framework for Fixing #1

### LINKED ISSUE #1: Feedback / Bug Report System
Add Feedback / Bug Report System to send the mail directly to Ajayprabhakar369@gmail.com

Also, Add when the app crashes it will automatically send the log messages about the crash

anyone can do this

### LINKED ISSUE #8: change the primary color
change the primary color of the app and experiment some colors

### PR DESCRIPTION
**Pull request by root-ansh**
This is the replacement PR for #16 .  

Commit 1 : Fixes #8 
- converted pictures to more flexible and small sized xmls
- added primary/secondry colors
- added changes in style.xml
- app now looks like this:  
img  

Commit 2: Fixes #1 
- added ACRA Framework. Highlighted the place where you have to add your email id (in MainApplication.java)
- there is something wrong with the spotless plugin. its causing my whole app to crash, but it was running fine on my other mobile.

### CODE REVIEW

**Comment by root-ansh** [comment]
wow not again

**Comment by root-ansh** [comment]
HAA! Finally 🎉

**Comment by ajay-prabhakar** [comment]
As you working on master branch itself so, your previous commit changes are also coming actually this is not good practice but As you are working on 2 issues make it them this PR itself 
I hope you know I to get solve build

**Review by ajay-prabhakar — APPROVED** [review]

**Comment by root-ansh** [comment]
Hi @Chromicle .  
I am not sure if I understood you correctly.  The first [commit](https://github.com/Chromicle/AmritaResource/pull/17/commits/524578d5bc53670a9a024efb28b72225af102625)  is for UI changes which got successfully built. The second [commit](https://github.com/Chromicle/AmritaResource/pull/17/commits/defc3c8ec696961540a158b068bc803923277c23) is for  Addition of ACRA which got rejected by travis-ci due to some spaces and tabs difference. The next few commits just changes these spaces and tabs to make travis ci work.   

I don't know if you can merge all these commits one by one or they will all get merged together, but i am sure the final merge won't give any errors(at least not compile time errors). I wanted to make another PR for 2nd( and subsequent) commits but they all got pushed to single PR( I am not much experienced with git, but i guess me adding directly into master is the correct explanation why it happened).  

Should I still make 2 different branches for these 2 Issues? I guess this would make some merging difficult for you only, since some classes  have been changed by both the commits

**Comment by ajay-prabhakar** [comment]
> Hi @Chromicle .
> I am not sure if I understood you correctly. The first [commit](https://github.com/Chromicle/AmritaResource/pull/17/commits/524578d5bc53670a9a024efb28b72225af102625) is for UI changes which got successfully built. The second [commit](https://github.com/Chromicle/AmritaResource/pull/17/commits/defc3c8ec696961540a158b068bc803923277c23) is for Addition of ACRA which got rejected by travis-ci due to some spaces and tabs difference. The next few commits just changes these spaces and tabs to make travis ci work.
> 
> I don't know if you can merge all these commits one by one or they will all get merged together, but i am sure the final merge won't give any errors(at least not compile time errors). I wanted to make another PR for 2nd( and subsequent) commits but they all got pushed to single PR( I am not much experienced with git, but i guess me adding directly into master is the correct explanation why it happened).
> 
> Should I still make 2 different branches for these 2 Issues? I guess this would make some merging difficult for you only, since some classes have been changed by both the commits

That is what I am saying make everything in one PR finally, I will merge everything

**Comment by root-ansh** [comment]
But , everything ***is*** in 1 PR.

**Comment by ajay-prabhakar** [comment]
Ok, I understood

**Review by ajay-prabhakar — APPROVED** [review]
🎉

**Pull request merged**
