### PR TITLE
Remove settings option

### PR DESCRIPTION
**Pull request by srijande**
ar

### CODE REVIEW

**Review by ajay-prabhakar — APPROVED** [review]
thanks for the PR good work, and Thank you for upgrading build also 😄

**Comment by ajay-prabhakar** [comment]
Just run `./gradlew spotlessApply` to fix your build then I will merge this

**Comment by srijande** [comment]
Done..
I have fixed build.

**Comment by ajay-prabhakar** [comment]
Thanks for the PR

**Pull request merged**
