### PR TITLE
Internet proper connection

### PR DESCRIPTION
**Pull request by rahmatsyam**
I add fitur check internet connection when downoading pdf

### CODE REVIEW

**Comment by rahmatsyam** [comment]
Screenshot_2019-10-06-07-31-45-035_com example android miwok

**Comment by rahmatsyam** [comment]
When downloading pdf and no internet connection, the alertdialog will show and press close you will be back to previous activity

**Comment by ajay-prabhakar** [comment]
Can you update the branch and resolve conflicts

**Comment by rahmatsyam** [comment]
Wait, I will try fix it

**Comment by rahmatsyam** [comment]
already fix

**Review by ajay-prabhakar — APPROVED** [review]
:tada: thankyou for  your contribution great work

**Pull request merged**
