### PR TITLE
Added Crash reporting system that would fix  #1 and added a unifying red color that would fix #8

### LINKED ISSUE #1: Feedback / Bug Report System
Add Feedback / Bug Report System to send the mail directly to Ajayprabhakar369@gmail.com

Also, Add when the app crashes it will automatically send the log messages about the crash

anyone can do this

### LINKED ISSUE #8: change the primary color
change the primary color of the app and experiment some colors

### PR DESCRIPTION
**Pull request by root-ansh**
Added ARCA crash reporting system that was highlighted in #1  in `MyApplication.java` file. You need to replace `EMAIL_TO` variable with your email id .  
Whenever a crash occurs, the library automatically takes all the crash logs, adds them in a file and opens gmail on user's mobile. User can now simply press the send button to send you his details.

### CODE REVIEW

**Comment by root-ansh** [comment]
Also, this Pr fixes #8  since i changed the color of all the main activity's items to red

**Comment by ajay-prabhakar** [comment]
Can you please provide any recording and please fix the travis issue you
If you are using linux run `./gradlew spotlessApply` for spotless issue

**Comment by root-ansh** [comment]
I am on a windows environment , I have never worked with travis-ci. This app is working fine on my machine. can you guide me how can i fix this travis ci issue?  

And about that recording sure, i will post this evening when I reach home

**Comment by ajay-prabhakar** [comment]
This is because of spotless plugin so open cmd and change directory to this repo and run `gradlew sptlessApply` you can fix this issue

**Comment by root-ansh** [comment]
```bash
08:27:51 PM: Executing tasks 'gradle sptlessApply'...

Executing tasks: [gradle, sptlessApply] in project P:\GIT_GITHUB\AmritaResource


FAILURE: Build failed with an exception.

* What went wrong:
Task 'gradle' not found in root project 'Amrita Resouce'. Some candidates are: 'bundle'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
08:27:52 PM: Tasks execution finished 'gradle sptlessApply'.

```

**Comment by root-ansh** [comment]
@Chromicle  I am getting this error:
```bash
08:27:51 PM: Executing tasks 'gradle sptlessApply'...

Executing tasks: [gradle, sptlessApply] in project P:\GIT_GITHUB\AmritaResource


FAILURE: Build failed with an exception.

* What went wrong:
Task 'gradle' not found in root project 'Amrita Resouce'. Some candidates are: 'bundle'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
08:27:52 PM: Tasks execution finished 'gradle sptlessApply'.

```

**Comment by root-ansh** [comment]
I am currently having issues with this repo. Let me Delete the fork and PR and try again

**Comment by ajay-prabhakar** [comment]
That is the error because you did not updated the project well 
Looking forward to your new PR

**Pull request closed without merging**
